Repository Picount-SOLUX/Picount-BE, pull requests merged in 2025-07, with the labels that each got.

#17 [FEAT] Spring Security, 회원가입, 로그인 기능 구현
  build.gradle
  http/auth.http
  src/main/java/com/solux/piccountbe/config/jwt/JwtTokenAuthenticationFilter.java
  src/main/java/com/solux/piccountbe/config/jwt/JwtTokenProvider.java
  src/main/java/com/solux/piccountbe/config/security/SecurityProperties.java
  src/main/java/com/solux/piccountbe/config/security/UserDetailsImpl.java
  src/main/java/com/solux/piccountbe/config/security/UserDetailsServiceImpl.java
  src/main/java/com/solux/piccountbe/config/security/WebSecurityConfig.java
  src/main/java/com/solux/piccountbe/domain/member/MemberController.java
  src/main/java/com/solux/piccountbe/domain/member/dto/LoginRequestDto.java
  src/main/java/com/solux/piccountbe/domain/member/dto/LoginResponseDto.java
  src/main/java/com/solux/piccountbe/domain/member/dto/SignupRequestDto.java
  src/main/java/com/solux/piccountbe/domain/member/entity/Member.java
  src/main/java/com/solux/piccountbe/domain/member/entity/Token.java
  src/main/java/com/solux/piccountbe/domain/member/repository/MemberRepository.java
  src/main/java/com/solux/piccountbe/domain/member/repository/TokenRepository.java
  src/main/java/com/solux/piccountbe/domain/member/service/MemberService.java
  src/main/java/com/solux/piccountbe/domain/member/service/TokenService.java
  src/main/java/com/solux/piccountbe/global/exception/ErrorCode.java
  src/main/java/com/solux/piccountbe/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: feat

#19 feat: #18 - findByFriendCode 추가, ErrorCode 추가
  src/main/java/com/solux/piccountbe/domain/member/repository/MemberRepository.java
  src/main/java/com/solux/piccountbe/domain/member/service/MemberService.java
  src/main/java/com/solux/piccountbe/global/exception/ErrorCode.java
Labels: feat

#24 [FEAT] 상품 구매, 보유 스킨 조회 api 구현
  src/main/java/com/solux/piccountbe/domain/item/controller/ItemController.java
  src/main/java/com/solux/piccountbe/domain/item/controller/MyItemController.java
  src/main/java/com/solux/piccountbe/domain/item/dto/ItemResponseDto.java
  src/main/java/com/solux/piccountbe/domain/item/dto/request/PurchaseRequestDto.java
  src/main/java/com/solux/piccountbe/domain/item/dto/response/ItemResponseDto.java
  src/main/java/com/solux/piccountbe/domain/item/dto/response/MyCakeDesignResponseDto.java
  src/main/java/com/solux/piccountbe/domain/item/dto/response/MyCalendarDesignResponseDto.java
  src/main/java/com/solux/piccountbe/domain/item/dto/response/MyWebSkinResponseDto.java
  src/main/java/com/solux/piccountbe/domain/item/dto/response/PurchaseResponseDto.java
  src/main/java/com/solux/piccountbe/domain/item/entity/Purchase.java
  src/main/java/com/solux/piccountbe/domain/item/repository/PurchaseRepository.java
  src/main/java/com/solux/piccountbe/domain/item/service/ItemService.java
  src/main/java/com/solux/piccountbe/domain/item/service/MyItemService.java
  src/main/java/com/solux/piccountbe/domain/member/entity/Member.java
  src/main/java/com/solux/piccountbe/domain/member/service/MemberService.java
  src/main/java/com/solux/piccountbe/domain/pointHistory/entity/PointHistory.java
  src/main/java/com/solux/piccountbe/domain/pointHistory/entity/Reason.java
  src/main/java/com/solux/piccountbe/domain/pointHistory/service/PointService.java
  src/main/java/com/solux/piccountbe/global/exception/ErrorCode.java
Labels: feat

#26 [FEAT] 전체 구매 목록 조회
  src/main/java/com/solux/piccountbe/domain/item/controller/MyItemController.java
  src/main/java/com/solux/piccountbe/domain/item/dto/response/MyPurchaseDto.java
  src/main/java/com/solux/piccountbe/domain/item/service/MyItemService.java
Labels: feat

#31 [FEAT] 메인페이지 공개 여부 필드 추가
  src/main/java/com/solux/piccountbe/domain/member/entity/Member.java
  src/main/java/com/solux/piccountbe/domain/member/service/MemberService.java
Labels: feat

#32 [FEAT] OAuth, 카카오 로그인
  build.gradle
  src/main/java/com/solux/piccountbe/config/jwt/JwtTokenAuthenticationFilter.java
  src/main/java/com/solux/piccountbe/config/jwt/JwtTokenProvider.java
  src/main/java/com/solux/piccountbe/config/oauth/OAuth2LoginFailureHandler.java
  src/main/java/com/solux/piccountbe/config/oauth/OAuth2LoginSuccessHandler.java
  src/main/java/com/solux/piccountbe/config/security/SecurityProperties.java
  src/main/java/com/solux/piccountbe/config/security/UserDetailsImpl.java
  src/main/java/com/solux/piccountbe/config/security/WebSecurityConfig.java
  src/main/java/com/solux/piccountbe/domain/member/controller/MemberController.java
  src/main/java/com/solux/piccountbe/domain/member/entity/Member.java
  src/main/java/com/solux/piccountbe/domain/member/repository/MemberRepository.java
  src/main/java/com/solux/piccountbe/domain/member/service/CustomOAuth2UserService.java
  src/main/java/com/solux/piccountbe/domain/member/service/MemberService.java
  src/main/java/com/solux/piccountbe/domain/member/service/TokenService.java
  src/main/java/com/solux/piccountbe/global/exception/ErrorCode.java
  src/main/resources/application.yml
  src/main/resources/static/login.html
Labels: feat

#35 [FEAT] 프로필 수정 / 프로필 조회
  http/auth.http
  src/main/java/com/solux/piccountbe/config/image/WebConfig.java
  src/main/java/com/solux/piccountbe/domain/member/controller/MemberController.java
  src/main/java/com/solux/piccountbe/domain/member/dto/EmailRequestDto.java
  src/main/java/com/solux/piccountbe/domain/member/dto/MemberGroupTypeRequestDto.java
  src/main/java/com/solux/piccountbe/domain/member/dto/ProfileResponseDto.java
  src/main/java/com/solux/piccountbe/domain/member/dto/ProfileUpdateRequestDto.java
  src/main/java/com/solux/piccountbe/domain/member/dto/SignupRequestDto.java
  src/main/java/com/solux/piccountbe/domain/member/entity/Gender.java
  src/main/java/com/solux/piccountbe/domain/member/entity/Member.java
  src/main/java/com/solux/piccountbe/domain/member/entity/MemberGroupType.java
  src/main/java/com/solux/piccountbe/domain/member/entity/Occupation.java
  src/main/java/com/solux/piccountbe/domain/member/service/CustomOAuth2UserService.java
  src/main/java/com/solux/piccountbe/domain/member/service/MemberService.java
  src/main/java/com/solux/piccountbe/global/exception/ErrorCode.java
  src/main/resources/application.yml
  src/main/resources/static/images/profile/default-member-profile.png
Labels: feat

#37 [FEAT] 예산 생성/삭제/조회
  http/auth.http
  http/budget.http
  src/main/java/com/solux/piccountbe/domain/budget/controller/BudgetController.java
  src/main/java/com/solux/piccountbe/domain/budget/dto/BudgetAllocationDto.java
  src/main/java/com/solux/piccountbe/domain/budget/dto/BudgetResponseDto.java
  src/main/java/com/solux/piccountbe/domain/budget/dto/CreateBudgetRequestDto.java
  src/main/java/com/solux/piccountbe/domain/budget/dto/GetAllBudgetResponseDto.java
  src/main/java/com/solux/piccountbe/domain/budget/dto/GetBudgetResponseDto.java
  src/main/java/com/solux/piccountbe/domain/budget/entity/Budget.java
  src/main/java/com/solux/piccountbe/domain/budget/repository/BudgetRepository.java
  src/main/java/com/solux/piccountbe/domain/budget/service/BudgetService.java
  src/main/java/com/solux/piccountbe/domain/member/entity/Member.java
  src/main/java/com/solux/piccountbe/global/exception/ErrorCode.java
Labels: feat

#40 Feature/#38 category crd
  http/category.http
  src/main/java/com/solux/piccountbe/domain/category/controller/CategoryController.java
  src/main/java/com/solux/piccountbe/domain/category/dto/CreateOrUpdateCategoryRequestDto.java
  src/main/java/com/solux/piccountbe/domain/category/dto/GetAllCategoryResponseDto.java
  src/main/java/com/solux/piccountbe/domain/category/dto/GetCategoryResponseDto.java
  src/main/java/com/solux/piccountbe/domain/category/entity/Category.java
  src/main/java/com/solux/piccountbe/domain/category/repository/CategoryRepository.java
  src/main/java/com/solux/piccountbe/domain/category/service/CategoryService.java
  src/main/java/com/solux/piccountbe/global/exception/ErrorCode.java
Labels: feat

#49 Feature/#43 logout token
  http/auth.http
  src/main/java/com/solux/piccountbe/config/jwt/JwtTokenAuthenticationFilter.java
  src/main/java/com/solux/piccountbe/config/jwt/JwtTokenProvider.java
  src/main/java/com/solux/piccountbe/config/oauth/OAuth2LoginSuccessHandler.java
  src/main/java/com/solux/piccountbe/config/security/WebSecurityConfig.java
  src/main/java/com/solux/piccountbe/domain/member/GenerateRandomCode.java
  src/main/java/com/solux/piccountbe/domain/member/controller/MemberController.java
  src/main/java/com/solux/piccountbe/domain/member/dto/PasswordRequestDto.java
  src/main/java/com/solux/piccountbe/domain/member/dto/RefreshRequestDto.java
  src/main/java/com/solux/piccountbe/domain/member/entity/Member.java
  src/main/java/com/solux/piccountbe/domain/member/service/CustomOAuth2UserService.java
  src/main/java/com/solux/piccountbe/domain/member/service/MemberService.java
  src/main/java/com/solux/piccountbe/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: feat

#51 Fix/#50 response
  http/budget.http
  http/category.http
  src/main/java/com/solux/piccountbe/domain/budget/controller/BudgetController.java
  src/main/java/com/solux/piccountbe/domain/budget/dto/BudgetResponseDto.java
  src/main/java/com/solux/piccountbe/domain/budget/service/BudgetService.java
  src/main/java/com/solux/piccountbe/domain/category/controller/CategoryController.java
  src/main/java/com/solux/piccountbe/domain/category/dto/GetCategoryResponseDto.java
  src/main/java/com/solux/piccountbe/domain/category/service/CategoryService.java
  src/main/java/com/solux/piccountbe/domain/member/controller/MemberController.java
  src/main/java/com/solux/piccountbe/domain/member/dto/ProfileResponseDto.java
  src/main/java/com/solux/piccountbe/domain/member/service/MemberService.java
Labels: fix

#58 [FEAT] cors 설정
  src/main/java/com/solux/piccountbe/config/image/WebConfig.java
  src/main/java/com/solux/piccountbe/config/security/WebSecurityConfig.java
Labels: feat

#68 [FEAT] 기본 이미지들 설정 (상점, 프로필)
  src/main/java/com/solux/piccountbe/config/S3/S3Config.java
  src/main/java/com/solux/piccountbe/config/S3/S3Controller.java
  src/main/java/com/solux/piccountbe/config/S3/S3UploadService.java
  src/main/java/com/solux/piccountbe/domain/item/service/ItemService.java
  src/main/java/com/solux/piccountbe/global/DefaultImageUtil.java
  src/main/java/com/solux/piccountbe/mock/item/CakeMockDataInitializer.java
  src/main/java/com/solux/piccountbe/mock/item/CalendarMockDataInitializer.java
  src/main/java/com/solux/piccountbe/mock/item/WebSkinMockDataInitializer.java
  src/main/resources/application.yml
Labels: feat

#71 [FEAT] S3 이미지 업로드
  src/main/java/com/solux/piccountbe/domain/member/controller/MemberController.java
  src/main/java/com/solux/piccountbe/domain/member/service/MemberService.java
Labels: feat

#73 [FIX] 비밀번호 암호화
  src/main/java/com/solux/piccountbe/domain/member/service/MemberService.java
Labels: fix

#75 [FEAT] 카테고리 다건생성 API
  http/category.http
  src/main/java/com/solux/piccountbe/domain/category/controller/CategoryController.java
  src/main/java/com/solux/piccountbe/domain/category/dto/AllCategoryResponseDto.java
  src/main/java/com/solux/piccountbe/domain/category/dto/CategoryRequestDto.java
  src/main/java/com/solux/piccountbe/domain/category/dto/CategoryResponseDto.java
  src/main/java/com/solux/piccountbe/domain/category/dto/CreateCategoryRequestDto.java
  src/main/java/com/solux/piccountbe/domain/category/service/CategoryService.java
Labels: feat

#77 [FEAT] 상품별 가격 설정
  src/main/java/com/solux/piccountbe/mock/item/CakeMockDataInitializer.java
  src/main/java/com/solux/piccountbe/mock/item/CalendarMockDataInitializer.java
  src/main/java/com/solux/piccountbe/mock/item/WebSkinMockDataInitializer.java
Labels: feat

#81 [STYLE] 상품 이미지 url 수정
  src/main/java/com/solux/piccountbe/mock/item/CalendarMockDataInitializer.java
  src/main/java/com/solux/piccountbe/mock/item/WebSkinMockDataInitializer.java
Labels: style
